# Generated by Django 6.0.7 on 2026-07-21 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practicas', '0002_empresa_horario_alumno'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='practicas.empresa'),
        ),
    ]
